// Menu Recovery Tool - Restores original comprehensive menu data
// This will overwrite any existing menu data and restore the original perfect menu

export const originalCanteen1Menu = [
  // Main Canteen - Complete Original Menu
  { item_id: 1, name: 'KL Biryani', description: 'Kerala style aromatic biryani with spices', price: 120, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 30, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 2, name: 'TN Biryani', description: 'Tamil Nadu style biryani with unique flavors', price: 110, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 25, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 3, name: 'Chicken Biryani', description: 'Traditional chicken biryani with basmati rice', price: 130, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 40, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 4, name: 'Mutton Biryani', description: 'Rich mutton biryani with tender meat pieces', price: 180, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 20, preparation_time: 35, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 5, name: 'Egg Biryani', description: 'Delicious egg biryani with aromatic spices', price: 90, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 35, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 6, name: 'Prawn Biryani', description: 'Coastal style prawn biryani', price: 160, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 15, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 7, name: 'Fish Biryani', description: 'Fresh fish biryani with coastal spices', price: 150, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 18, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 8, name: 'Veg Biryani', description: 'Mixed vegetable biryani with aromatic rice', price: 80, category: 'Biryani', is_veg: true, is_available: true, available_quantity: 45, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 9, name: 'Chicken Fried Rice', description: 'Wok-tossed rice with chicken and vegetables', price: 100, category: 'Fried Rice', is_veg: false, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 10, name: 'Mutton Fried Rice', description: 'Spicy mutton fried rice', price: 140, category: 'Fried Rice', is_veg: false, is_available: true, available_quantity: 22, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 11, name: 'Egg Fried Rice', description: 'Classic egg fried rice with vegetables', price: 70, category: 'Fried Rice', is_veg: false, is_available: true, available_quantity: 40, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 12, name: 'Veg Fried Rice', description: 'Mixed vegetable fried rice', price: 60, category: 'Fried Rice', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 13, name: 'Chicken Curry with Rice', description: 'Spicy chicken curry served with steamed rice', price: 110, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 35, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 14, name: 'Mutton Curry with Rice', description: 'Rich mutton curry with rice', price: 150, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 25, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 15, name: 'Fish Curry Meals', description: 'Traditional fish curry with rice', price: 120, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 20, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 16, name: 'Egg Curry with Rice', description: 'Egg curry in spicy gravy with rice', price: 80, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 17, name: 'Chicken 65', description: 'Spicy fried chicken starter', price: 120, category: 'Starters', is_veg: false, is_available: true, available_quantity: 25, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 18, name: 'Chicken Kebab', description: 'Grilled chicken kebab with spices', price: 140, category: 'Starters', is_veg: false, is_available: true, available_quantity: 20, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 19, name: 'Mutton Kebab', description: 'Tender mutton kebab', price: 160, category: 'Starters', is_veg: false, is_available: true, available_quantity: 15, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 20, name: 'Fish Fry', description: 'Crispy fried fish pieces', price: 130, category: 'Starters', is_veg: false, is_available: true, available_quantity: 18, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 21, name: 'Curd Rice', description: 'Cooling curd rice with tempering', price: 50, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 60, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 22, name: 'Lemon Rice', description: 'Tangy lemon rice with nuts', price: 55, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 45, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 23, name: 'Tamarind Rice', description: 'Spicy tamarind rice', price: 60, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 24, name: 'Tomato Rice', description: 'Flavorful tomato rice', price: 55, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 42, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 25, name: 'Idli with Sambar', description: 'Steamed idli with sambar and chutney', price: 40, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 80, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 26, name: 'Vada with Chutney', description: 'Crispy vada with coconut chutney', price: 35, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 70, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 27, name: 'Dosa with Chutney', description: 'Crispy dosa with chutneys and sambar', price: 50, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 55, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 28, name: 'Masala Dosa', description: 'Dosa stuffed with spiced potato filling', price: 65, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 29, name: 'Paneer Butter Masala with Roti', description: 'Creamy paneer curry with rotis', price: 130, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 30, name: 'Chole Bhature', description: 'Spicy chickpea curry with fried bread', price: 90, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];

export const originalCanteen2Menu = [
  // IT Canteen - Complete Original Menu  
  { item_id: 31, name: 'KL Biryani', description: 'Kerala style aromatic biryani', price: 115, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 25, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 32, name: 'TN Biryani', description: 'Tamil Nadu style biryani', price: 105, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 22, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 33, name: 'Chicken Biryani', description: 'Traditional chicken biryani', price: 125, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 35, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 34, name: 'Mutton Biryani', description: 'Rich mutton biryani', price: 175, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 15, preparation_time: 35, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 35, name: 'Egg Biryani', description: 'Egg biryani with spices', price: 85, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 30, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 36, name: 'Prawn Biryani', description: 'Coastal prawn biryani', price: 155, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 12, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 37, name: 'Fish Biryani', description: 'Fresh fish biryani', price: 145, category: 'Biryani', is_veg: false, is_available: true, available_quantity: 15, preparation_time: 30, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 38, name: 'Veg Biryani', description: 'Mixed vegetable biryani', price: 75, category: 'Biryani', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 39, name: 'Paneer Biryani', description: 'Paneer biryani with aromatic rice', price: 110, category: 'Biryani', is_veg: true, is_available: true, available_quantity: 25, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 40, name: 'Chicken Fried Rice', description: 'Chicken fried rice with vegetables', price: 95, category: 'Fried Rice', is_veg: false, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 41, name: 'Mutton Curry with Rice', description: 'Mutton curry served with rice', price: 145, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 20, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 42, name: 'Fish Curry Meals', description: 'Fish curry with steamed rice', price: 115, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 18, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 43, name: 'Chicken Curry with Roti', description: 'Chicken curry with fresh rotis', price: 105, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 25, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 44, name: 'Egg Curry', description: 'Spicy egg curry', price: 70, category: 'Curry Meals', is_veg: false, is_available: true, available_quantity: 35, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 45, name: 'Chicken 65', description: 'Spicy fried chicken pieces', price: 115, category: 'Starters', is_veg: false, is_available: true, available_quantity: 20, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 46, name: 'Chicken Kebab', description: 'Grilled chicken kebab', price: 135, category: 'Starters', is_veg: false, is_available: true, available_quantity: 18, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 47, name: 'Mutton Kebab', description: 'Tender mutton kebab', price: 155, category: 'Starters', is_veg: false, is_available: true, available_quantity: 12, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 48, name: 'Fish Fry', description: 'Crispy fish fry', price: 125, category: 'Starters', is_veg: false, is_available: true, available_quantity: 15, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 49, name: 'Curd Rice', description: 'Cooling curd rice', price: 45, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 50, name: 'Lemon Rice', description: 'Tangy lemon rice', price: 50, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 51, name: 'Tomato Rice', description: 'Spicy tomato rice', price: 50, category: 'South Indian', is_veg: true, is_available: true, available_quantity: 38, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 52, name: 'Paneer Butter Masala with Roti', description: 'Paneer curry with rotis', price: 125, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 30, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 53, name: 'Chole Bhature', description: 'Chickpea curry with bhature', price: 85, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 25, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 54, name: 'Aloo Paratha', description: 'Stuffed potato paratha', price: 60, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 55, name: 'Gobi Paratha', description: 'Cauliflower stuffed paratha', price: 65, category: 'North Indian', is_veg: true, is_available: true, available_quantity: 32, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 56, name: 'Samosa', description: 'Crispy fried samosa', price: 12, category: 'Snacks', is_veg: true, is_available: true, available_quantity: 100, preparation_time: 5, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 57, name: 'Pav Bhaji', description: 'Spicy vegetable curry with bread', price: 70, category: 'Snacks', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 58, name: 'Pani Puri', description: 'Crispy puris with spicy water', price: 30, category: 'Snacks', is_veg: true, is_available: true, available_quantity: 60, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 59, name: 'Vada Pav', description: 'Mumbai style vada pav', price: 25, category: 'Snacks', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];

export const originalCanteen3Menu = [
  // MBA Canteen - Complete Vegetarian Menu
  { item_id: 60, name: 'Veg Biryani', description: 'Premium vegetable biryani', price: 90, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 61, name: 'Paneer Biryani', description: 'Aromatic paneer biryani', price: 120, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 62, name: 'Mushroom Biryani', description: 'Exotic mushroom biryani', price: 110, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 30, preparation_time: 25, image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 63, name: 'Curd Rice', description: 'Traditional curd rice', price: 55, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 60, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 64, name: 'Lemon Rice', description: 'Zesty lemon rice', price: 60, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 45, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 65, name: 'Tamarind Rice', description: 'Tangy tamarind rice', price: 65, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 66, name: 'Tomato Rice', description: 'Flavorful tomato rice', price: 60, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 42, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 67, name: 'Veg Fried Rice', description: 'Mixed vegetable fried rice', price: 70, category: 'Rice & Biryani', is_veg: true, is_available: true, available_quantity: 55, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 68, name: 'Idli', description: 'Soft steamed idli with sambar and chutney', price: 45, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 80, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 69, name: 'Vada', description: 'Crispy vada with chutneys', price: 40, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 70, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 70, name: 'Dosa', description: 'Crispy plain dosa', price: 55, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 60, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 71, name: 'Masala Dosa', description: 'Dosa with spiced potato filling', price: 70, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 72, name: 'Onion Dosa', description: 'Dosa topped with onions', price: 65, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 45, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 73, name: 'Rava Dosa', description: 'Crispy semolina dosa', price: 75, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 74, name: 'Uttapam', description: 'Thick pancake with toppings', price: 60, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 75, name: 'Pongal', description: 'Traditional rice and lentil dish', price: 50, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 76, name: 'Upma', description: 'Savory semolina upma', price: 40, category: 'South Indian Specials', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 10, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 77, name: 'Paneer Butter Masala', description: 'Creamy paneer curry', price: 140, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 78, name: 'Palak Paneer', description: 'Paneer in spinach gravy', price: 130, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 79, name: 'Chole Bhature', description: 'Spicy chickpeas with bhature', price: 95, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 30, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 80, name: 'Rajma Chawal', description: 'Kidney bean curry with rice', price: 85, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 20, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 81, name: 'Aloo Paratha', description: 'Potato stuffed paratha', price: 65, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 45, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 82, name: 'Gobi Paratha', description: 'Cauliflower stuffed paratha', price: 70, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 40, preparation_time: 12, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 83, name: 'Paneer Paratha', description: 'Paneer stuffed paratha', price: 80, category: 'North Indian & Curries', is_veg: true, is_available: true, available_quantity: 35, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 84, name: 'Samosa', description: 'Crispy vegetable samosa', price: 15, category: 'Snacks & Street Food', is_veg: true, is_available: true, available_quantity: 100, preparation_time: 5, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 85, name: 'Pav Bhaji', description: 'Mumbai style pav bhaji', price: 75, category: 'Snacks & Street Food', is_veg: true, is_available: true, available_quantity: 50, preparation_time: 15, image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { item_id: 86, name: 'Pani Puri', description: 'Crispy puris with flavored water', price: 35, category: 'Snacks & Street Food', is_veg: true, is_available: true, available_quantity: 80, preparation_time: 8, image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&h=200&fit=crop', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];

// Recovery function to restore original menu data
export function restoreOriginalMenus() {
  console.log('🔄 Restoring original menu data...');
  
  // Clear any existing corrupted data
  localStorage.removeItem('mockMenuItems');
  localStorage.removeItem('canteen_1_menu');
  localStorage.removeItem('canteen_2_menu');
  localStorage.removeItem('canteen_3_menu');
  
  // Store individual canteen menus
  localStorage.setItem('canteen_1_menu', JSON.stringify(originalCanteen1Menu));
  localStorage.setItem('canteen_2_menu', JSON.stringify(originalCanteen2Menu));
  localStorage.setItem('canteen_3_menu', JSON.stringify(originalCanteen3Menu));
  
  // Create combined admin menu (all canteens combined for admin management)
  const combinedAdminMenu = [
    ...originalCanteen1Menu,
    ...originalCanteen2Menu,
    ...originalCanteen3Menu
  ];
  
  localStorage.setItem('mockMenuItems', JSON.stringify(combinedAdminMenu));
  
  console.log('✅ Original menu data restored successfully!');
  console.log(`📊 Restored ${originalCanteen1Menu.length} items for Main Canteen`);
  console.log(`📊 Restored ${originalCanteen2Menu.length} items for IT Canteen`);
  console.log(`📊 Restored ${originalCanteen3Menu.length} items for MBA Canteen`);
  console.log(`📊 Total: ${combinedAdminMenu.length} items`);
  
  return {
    canteen1: originalCanteen1Menu.length,
    canteen2: originalCanteen2Menu.length,
    canteen3: originalCanteen3Menu.length,
    total: combinedAdminMenu.length
  };
}

// Function to get canteen-specific menu
export function getCanteenMenu(canteenId: number) {
  switch (canteenId) {
    case 1: return originalCanteen1Menu;
    case 2: return originalCanteen2Menu;
    case 3: return originalCanteen3Menu;
    default: return [];
  }
}